<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-Jas-121e4349-ecf8-4ee9-aeff-718145dd30b9</UserSecretsId>
    <SatelliteResourceLanguages>cs</SatelliteResourceLanguages>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Data\JasMtzDb\JasMtzDbContext.Partial.cs" />
    <Compile Remove="Data\JasMtzDb\MtzProduct.Partial.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <Content Remove="wwwroot\css\srv.less" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Areas\Ptg\Pages\_PlateContent.cshtml" />
    <None Include="compilerconfig.json" />
    <None Include="Php\home\vendor\contributte\forms-multiplier\.github\.kodiak.toml" />
    <None Include="Php\home\vendor\contributte\forms-multiplier\.github\workflows\main.yaml" />
    <None Include="Php\home\vendor\contributte\menu-control\.docs\README.md" />
    <None Include="Php\home\vendor\contributte\pdf\.docs\README.md" />
    <None Include="Php\home\vendor\contributte\pdf\.github\.kodiak.toml" />
    <None Include="Php\home\vendor\contributte\pdf\.github\FUNDING.yml" />
    <None Include="Php\home\vendor\contributte\pdf\.github\workflows\tests.yml" />
    <None Include="Php\home\vendor\maennchen\zipstream-php\.github\FUNDING.yml" />
    <None Include="Php\home\vendor\maennchen\zipstream-php\.github\ISSUE_TEMPLATE.md" />
    <None Include="Php\home\vendor\markbaker\complex\.github\workflows\main.yml" />
    <None Include="Php\home\vendor\markbaker\matrix\.github\workflows\main.yaml" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\CONTRIBUTING.md" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\FUNDING.yml" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\ISSUE_TEMPLATE\Bug_report.md" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\ISSUE_TEMPLATE\config.yml" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\ISSUE_TEMPLATE\Feature_request.md" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\workflows\coverage.yml" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\workflows\cs.yml" />
    <None Include="Php\home\vendor\mpdf\mpdf\.github\workflows\tests.yml" />
    <None Include="Php\home\vendor\myclabs\deep-copy\.github\FUNDING.yml" />
    <None Include="wwwroot\css\srv.less" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="AutoMapper.Data" Version="10.0.0" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DinkToPdf" Version="1.0.8" />
    <PackageReference Include="jQuery.UI.Combined" Version="1.14.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.jQuery.Unobtrusive.Ajax" Version="3.2.6" />
    <PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
    <PackageReference Include="Microsoft.Win32.Primitives" Version="4.3.0" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.3" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
    <PackageReference Include="System.Net.Primitives" Version="4.3.1" />
    <PackageReference Include="X.PagedList" Version="10.5.9" />
    <PackageReference Include="X.PagedList.EF" Version="10.5.9" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="10.5.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Pdf\Pages\Shared\DisplayTemplates\" />
    <Folder Include="Areas\Pdf\Pages\Shared\EditorTemplates\" />
    <Folder Include="Areas\Ptg\Pages\Shared\EditorTemplates\" />
    <Folder Include="Areas\Srv\Pages\Shared\DisplayTemplates\" />
    <Folder Include="Areas\Srv\Pages\Shared\EditorTemplates\" />
    <Folder Include="Php\home\bin\" />
    <Folder Include="Php\home\vendor\tracy\tracy\examples\log\" />
    <Folder Include="Php\www\upload\" />
    <Folder Include="wwwroot\pdf\src\akce-koupelnove-vybaveni-2026\" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Php\home\vendor\nextras\dbal\.idea\codeStyles\codeStyleConfig.xml" />
    <Content Include="Php\home\vendor\nextras\dbal\.idea\codeStyles\Project.xml" />
    <Content Include="Php\home\vendor\nextras\dbal\.idea\sqldialects.xml" />
    <Content Include="Php\home\vendor\nextras\orm\.idea\codeStyles\codeStyleConfig.xml" />
    <Content Include="Php\home\vendor\nextras\orm\.idea\codeStyles\Project.xml" />
    <Content Include="Php\home\vendor\nextras\orm\.idea\sqldialects.xml" />
    <Content Include="Ps1\EmailSheduler.ps1">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Sql\EmailQueueStand.create.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Sql\sp_ptg_QueueStandChangeEmail.full.alter.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="Sql\sp_ptg_QueueStandChangeEmail.alter.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Update="Php\**\*">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
    <Content Update="wwwroot\pdf\ptg\**\*">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
